[build]
  command = "npm run build"
  publish = "build"
  base = "frontend"

[build.environment]
  REACT_APP_API_URL = "https://conference-management-l4zg.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 